name: Build and Deploy Docs
on: [push]
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: Docs/_html # The folder the action should deploy.
        BUILD_SCRIPT: # The build script the action should run prior to deploying.
            sudo apt-get install mono-complete
            wget https://www.naturaldocs.org/download/natural_docs/2.0.2/Natural_Docs_2.0.2.zip -O /tmp/ND.zip
            unzip /tmp/ND.zip -d /tmp
            mono "/tmp/Natural Docs/NaturalDocs.exe" Docs
