name: Build and Deploy Docs
on:
  push:
    branches:    
      - master 
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: wget ND
      uses: wei/wget@v1
      with:
        args: https://www.naturaldocs.org/download/natural_docs/2.0.2/Natural_Docs_2.0.2.zip -O ND.zip
    - name: Unzip ND
      run: unzip ND.zip -d ./
    - name: Build Docs
      run: mkdir Docs/_html && mono "./Natural Docs/NaturalDocs.exe" Docs
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: Docs/_html