name: Build and Deploy Docs
on: [push]
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: wget ND
      uses: wei/wget@v1
      with:
        args: -O https://www.naturaldocs.org/download/natural_docs/2.0.2/Natural_Docs_2.0.2.zip -O ND.zip
    - name: Unzip ND
      run: unzip ND.zip -d ./
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: Docs/_html # The folder the action should deploy.
        BUILD_SCRIPT: mono "./Natural Docs/NaturalDocs.exe" Docs
